[project]
name = "chatty-g-goes-to-the-market"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "feedparser>=6.0.11",
    "openai>=1.99.6",
    "python-dotenv>=1.1.1",
    "ruff>=0.12.8",
    "yfinance>=0.2.65",
]
